os: linux
dist: xenial
language: node_js

node_js:
    - '10'

env:
    - DIRTY_SNAPSHOTS=0

cache:
    npm: false

addons:
    hosts:
        - localhost.paypal.com

before_install:
    - npm i -g npm@6

before_script:
    - npm run dev:standalone &
    # Give dev server time to startup
    - sleep 40

jobs:
    include:
        - name: 'Lint, Unit and Non-Snap Tests'
          script:
              - npm run lint
              - npm run test
              - npm run test:func:nosnaps

        - name: 'Update Snapshots'
          if: env(DIRTY_SNAPSHOTS) = 1
          script:
              - ./scripts/snapshot-tests/update-snapshots.sh

        - name: 'Functional Tests'
          env:
              - TEST_PATH_PATTERN=spec/DE/banner
              - TEST_PATH_PATTERN=spec/DE/modal
              - TEST_PATH_PATTERN=spec/GB/banner
              - TEST_PATH_PATTERN=spec/GB/modal
              - TEST_PATH_PATTERN=spec/US/custom-and-legacy
              - TEST_PATH_PATTERN=spec/US/banner
              - TEST_PATH_PATTERN=spec/US/modal
          if: env(DIRTY_SNAPSHOTS) = 0
          script:
              - echo $TEST_PATH_PATTERN
              - npm run test:func -- --testPathPattern $TEST_PATH_PATTERN
              - ./scripts/snapshot-tests/run-tests-by-pattern.sh
              - ./scripts/snapshot-tests/collect-diffs.sh

deploy:
    provider: script
    skip_cleanup: true
    script:
        - npx semantic-release@15
    on:
        branch: release
