os: linux
dist: xenial
language: node_js

node_js:
    - '10'

env:
    - DIRTY_SNAPSHOTS=0

cache:
    npm: false

addons:
    hosts:
        - localhost.paypal.com

before_install:
    - npm i -g npm@6

# before_script:
#     # TODO: Re-enable once snapshot tests are reliably improved
#     - npm run dev:standalone &
#     # Give dev server time to startup
#     # TODO: Re-enable once snapshot tests are reliably improved
#     - sleep 40

# script:
#     - npm run lint
#     - npm run test
#     # TODO: Re-enable once snapshot tests are reliably improved
#     - npm run test:
#     - ./scripts/snapshot-tests/run-tests.sh

jobs:
    include:
        - name: 'Lint, Unit and Non-Snap Tests'
          script:
              - npm run lint
              - npm run test
              - npm run test:func:nosnaps
        - name: 'Update Snapshots'
          if: env(DIRTY_SNAPSHOTS) = 1
          script:
              - ./scripts/snapshot-tests/update-snapshots.sh

        # DE
        - name: 'Functional DE Banner Tests'
          if: env(DIRTY_SNAPSHOTS) = 0
          before_script:
              # TODO: Re-enable once snapshot tests are reliably improved
              - npm run dev:standalone &
              # Give dev server time to startup
              # TODO: Re-enable once snapshot tests are reliably improved
              - sleep 40
          script:
              - npm run test:func -- --testPathPattern spec/DE/banner
              - ./scripts/snapshot-tests/collect-diffs.sh
        - name: 'Functional DE Modal Tests'
          if: env(DIRTY_SNAPSHOTS) = 0
          before_script:
              # TODO: Re-enable once snapshot tests are reliably improved
              - npm run dev:standalone &
              # Give dev server time to startup
              # TODO: Re-enable once snapshot tests are reliably improved
              - sleep 40
          script:
              - npm run test:func -- --testPathPattern spec/DE/modal
              - ./scripts/snapshot-tests/collect-diffs.sh

        # GB
        - name: 'Functional GB Banner Tests'
          if: env(DIRTY_SNAPSHOTS) = 0
          before_script:
              # TODO: Re-enable once snapshot tests are reliably improved
              - npm run dev:standalone &
              # Give dev server time to startup
              # TODO: Re-enable once snapshot tests are reliably improved
              - sleep 40
          script:
              - npm run test:func -- --testPathPattern spec/GB/banner
              - ./scripts/snapshot-tests/collect-diffs.sh
        - name: 'Functional GB Modal Tests'
          if: env(DIRTY_SNAPSHOTS) = 0
          before_script:
              # TODO: Re-enable once snapshot tests are reliably improved
              - npm run dev:standalone &
              # Give dev server time to startup
              # TODO: Re-enable once snapshot tests are reliably improved
              - sleep 40
          script:
              - npm run test:func -- --testPathPattern spec/GB/modal
              - ./scripts/snapshot-tests/collect-diffs.sh

        # US
        - name: 'Functional US Banner Tests'
          if: env(DIRTY_SNAPSHOTS) = 0
          before_script:
              # TODO: Re-enable once snapshot tests are reliably improved
              - npm run dev:standalone &
              # Give dev server time to startup
              # TODO: Re-enable once snapshot tests are reliably improved
              - sleep 40
          script:
              - npm run test:func -- --testPathPattern spec/US/banner
              - ./scripts/snapshot-tests/collect-diffs.sh
        - name: 'Functional US Modal Tests'
          if: env(DIRTY_SNAPSHOTS) = 0
          before_script:
              # TODO: Re-enable once snapshot tests are reliably improved
              - npm run dev:standalone &
              # Give dev server time to startup
              # TODO: Re-enable once snapshot tests are reliably improved
              - sleep 40
          script:
              - npm run test:func -- --testPathPattern spec/US/modal
              - ./scripts/snapshot-tests/collect-diffs.sh
        - name: 'Functional US Custom/Legacy Tests'
          if: env(DIRTY_SNAPSHOTS) = 0
          before_script:
              # TODO: Re-enable once snapshot tests are reliably improved
              - npm run dev:standalone &
              # Give dev server time to startup
              # TODO: Re-enable once snapshot tests are reliably improved
              - sleep 40
          script:
              - npm run test:func -- --testPathPattern spec/US/custom-and-legacy
              - ./scripts/snapshot-tests/collect-diffs.sh

deploy:
    provider: script
    skip_cleanup: true
    script:
        - npx semantic-release@15
    on:
        branch: release
